version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - DB_PORT=3306
     - DB_HOST= $DB_HOST
     - DB_USER_NAME=admin
     - DB_PASSWORD=$DB_PASSWORD
     - DB_NAME=ChatApp      
    ports:
      - "80:80"