version: '3'
services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   # environment:
  #   #  - DB_PORT=3306
  #   #  - DB_HOST= $DB_HOST
  #   #  - DB_USER_NAME=admin
  #   #  - DB_PASSWORD=$DB_PASSWORD
    #  - DB_NAME=ChatApp     


  app:
    container_name: app-docker
    build: .
    environment:
      - PORT= 5000
      - DB_PASSWORD= ${{ secrets.DB_PASSWORD }}
      - GIT_VERSISON= ${{ needs.build.outputs.image_version }}
      - DB_HOST= ${{ secrets.DB_HOST }}
      - DB_PORT= ${{ secrets.DB_PORT }}
      - DB_USER_NAME= ${{ secrets.DB_USER_NAME }}
      - DB_NAME= ${{ secrets.DB_NAME }}
      - AWS_ACCESS_KEY_ID= ${{ secrets.AWS_ACCESS_KEY_ID }}
      - AWS_SECRET_ACCESS_KEY= ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - AWS_REGION= ${{ secrets.AWS_REGION }}
      - AWS_SES_ACESS_KEY_ID= ${{ secrets.AWS_SES_ACCESS_KEY_ID }}
      - AWS_SES_SECRET_ACCESS_KEY= ${{ secrets.AWS_SES_SECRET_ACCESS_KEY }}
      - AWS_SES_REGION= ${{ secrets.AWS_SES_REGION }}



    ports:
      - "5000:80"