version: '3'
services:
  app:
    container_name: app-docker
    image: realtimechat-1-app:latest

    environment:
      - PORT= 5000
      - DB_PASSWORD= $DB_PASSWORD
      - DB_HOST= $DB_HOST 
      - DB_PORT= $DB_PORT
      - DB_USER_NAME= $DB_USER_NAME 
      - DB_NAME= $DB_NAME
      - AWS_ACCESS_KEY_ID= $AWS_ACCESS_KEY_ID 
      - AWS_SECRET_ACCESS_KEY= $AWS_SECRET_ACCESS_KEY 
      - AWS_REGION= $AWS_REGION 
      - AWS_SES_ACCESS_KEY= $AWS_SES_ACCESS_KEY
      - AWS_SES_SECRET_ACCESS_KEY= $AWS_SES_SECRET_ACCESS_KEY 
      - AWS_SES_REGION= $AWS_SES_REGION 
    ports:
      - "80:5000"
    healthcheck:
      test: ["CMD", "curl", "http://localhost"]
      timeout: 20s
      retries: 5
    restart: always
     
