version: '3'
services:
  app:
    image: ghcr.io/somecoder23/realtimechat:$GIT_VERSION
    mem_limit: 5g
    restart: always 
    environment:
      - PORT= 5000
      - DB_PASSWORD= $DB_PASSWORD
      - DB_HOST= $DB_HOST 
      - DB_PORT= $DB_PORT
      - DB_USER_NAME= $DB_USER_NAME 
      - DB_NAME= $DB_NAME
      - AWS_ACCESS_KEY_ID= $AWS_ACCESS_KEY_ID 
      - AWS_SECRET_ACCESS_KEY= $AWS_SECRET_ACCESS_KEY 
      - AWS_REGION= $AWS_REGION 
      - AWS_SES_ACCESS_KEY= $AWS_SES_ACCESS_KEY
      - AWS_SES_SECRET_ACCESS_KEY= $AWS_SES_SECRET_ACCESS_KEY 
      - AWS_SES_REGION= $AWS_SES_REGION 

    ports:
      - "80:5000"