version: '3'
services:
  web:
    image:  ghcr.io/somecoder23/realtimechat:$GIT_VERSION
    restart: always
    environment:
     - DB_PORT=3306
     - DB_HOST= $DB_HOST
     - DB_USER_NAME=admin
     - DB_PASSWORD=$DB_PASSWORD
     - DB_NAME=ChatApp
    ports:
      - "80:5000"