version: '3'
services:

  app:
    container_name: realtimechat-1-web-1
    image: ghcr.io/somecoder23/realtimechat:$GIT_VERSION
    restart: always
    environment:
      - PORT=80
      - DB_HOST=localhost
      - DB_USER_NAME=root
      - DB_PASSWORD=''
      - DB_NAME=chatapp
    ports:
      - "5000:80"

    
