version: '3'
services:
  app:
    image: ghcr.io/somecoder23/realtimechat:$GIT_VERSION
    ports:
      - "5000:80"
    environment:
      - PORT=80
      - DB_HOST=localhost  
      - DB_USER_NAME=root 
      - DB_PASSWORD=''  
      - DB_NAME=chatapp
  db:
    image: ghcr.io/somecoder23/realtimechat:$GIT_VERSION
    environment:
      - PORT=80
      - DB_HOST=localhost  
      - DB_USER_NAME=root  
      - DB_PASSWORD='' 
      - DB_NAME=chatapp

