name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 13.53.134.121 >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@13.53.134.121 "echo SSH connection established"
      
      - name: Deploy Docker container
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@13.53.134.121 "docker stop chatapp || true"
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@13.53.134.121 "docker rm chatapp || true"
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@13.53.134.121 "docker pull somecoder23/chatapp:latest"
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@13.53.134.121 "docker run -d -p 80:80 --name chatapp somecoder23/chatapp:latest"

      - name: Push to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t somecoder23/chatapp:latest .
          docker push somecoder23/chatapp:latest
