name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build . -t somecoder23/chatapp-docker:${{ github.sha }}

      - name: Login to Docker Hub
        run: echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin



      - name: Push Docker image
        run: docker push somecoder23/chatapp-docker:${{ github.sha }}